### ISSUE TITLE
10 - workflow-scripts.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#10]
Tradução: @nextmarte 
Revisão 1: @beatrizmilz 
Revisão 2: @brunomioto

**Comment by nextmarte** [comment]
Posso fazer esse essa semana.

**Comment by Luaaalex** [comment]
@beatrizmilz, quando estiver finalizada essa tradução, eu posso seguir com a revisão :)

**Comment by beatrizmilz** [comment]
Oi @nextmarte ! Tudo bem? Como anda a tradução desse capítulo? Precisa de algo? Obrigada!

**Comment by nextmarte** [comment]
> Oi [@nextmarte](https://github.com/nextmarte) ! Tudo bem? Como anda a tradução desse capítulo? Precisa de algo? Obrigada!

Oi Bea, vou fazer essa semana, só consegui um tempinho agora.

**Comment by beatrizmilz** [comment]
@Luaaalex a tradução está completa! Pode fazer a revisão quando puder :)

**Comment by brunomioto** [comment]
Posso revisar @beatrizmilz !

**Comment by beatrizmilz** [comment]
Ok!! Obrigadaa!

**Comment by beatrizmilz** [comment]
Uhul! está no ar a versão em Português!

https://cienciadedatos.github.io/pt-r4ds/workflow-scripts.html

Obrigada @brunomioto @nextmarte !
