### ISSUE TITLE
11 - data-import.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#11]
Tradução: @albersonmiranda 
Revisão 1: @beatrizccolvara
Revisão 2: @beatrizmilz

**Comment by albersonmiranda** [comment]
@beatrizmilz , me atribui esse, por favor!

**Comment by beatrizmilz** [comment]
Oi @albersonmiranda  ! Tudo bem? Como anda a tradução desse capítulo? Precisa de algo? Obrigada!

**Comment by albersonmiranda** [comment]
> Oi @albersonmiranda ! Tudo bem? Como anda a tradução desse capítulo? Precisa de algo? Obrigada!

Esqueci não! Só resolvendo os últimos preparativos pra minha defesa (que é dia 29 😵) e já volto pra cá

**Comment by beatrizmilz** [comment]
Oi Alberson! Tudo bem? Espero que tenha dado tudo certo na defesa 🙏 
@albersonmiranda Sobre a tradução: Tem alguma novidade?
Se você estiver sem disponibilidade, você pode enviar o que já foi feito, e a gente continua com outra pessoa, sem problemas!

**Comment by albersonmiranda** [comment]
Ei, @beatrizmilz ! Deu tudo certo sim e o primeiro artigo já foi submetido! 🙏
Sobre a tradução, consegui retomar ontem e até mandei uma dúvida lá no canal (imagino que por isso o ping 😅)
