### ISSUE TITLE
14 - layers.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#14]
Tradução: @fernandaperes 
Revisão 1: @Luaaalex 
Revisão 2: @cesar-galvao

**Comment by fernandaperes** [comment]
Olá! Quero traduzir esse capítulo!

**Comment by beatrizmilz** [comment]
Oi @fernandaperes ! Uhuuul, vai ser ótimo ter sua contribuição.
No Wiki deste repositório, existem orientações sobre como fazer a tradução.
Caso tenha alguma dúvida, me avise!
Obrigada 🥰

**Comment by Luaaalex** [comment]
@beatrizmilz pode me colocar como revisora desse capítulo, por favor, quando a tradução for finalizada.

**Comment by cesar-galvao** [comment]
@beatrizmilz Pode me botar de segundo revisor desse?

**Comment by beatrizmilz** [comment]
> @beatrizmilz Pode me botar de segundo revisor desse?

Com certeza! Obrigada!

**Comment by beatrizmilz** [comment]
Fe, mil desculpas pela demora!
está no ar!
https://cienciadedatos.github.io/pt-r4ds/layers.html
