### ISSUE TITLE
16 - communication.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#16]
Tradução: @scopinho 
Revisão 1: @cmusso86 [cmusso86](https://github.com/cmusso86)
Revisão 2: @cesar-galvao

**Comment by scopinho** [comment]
**Tradução:** @scopinho
**Revisão 1:** 
**Revisão 2:**

**Comment by scopinho** [comment]
oi @beatrizmilz . Versão inicial da tradução submetida no[ PR 80](https://github.com/cienciadedatos/pt-r4ds/pull/80).
Liberado para iniciar a revisão. Thx

**Comment by beatrizmilz** [comment]
> @beatrizmilz , pode me colocar como segunda revisora também.

Adicionada <3

**Comment by beatrizmilz** [comment]
Oi @Luaaalex ! Tudo bem?
Eu sei que nessa época você está bem corrida com a mudança de país. 
Quer que eu libere seu nome dessa revisão, para outra pessoa revisar?
Abraços!

**Comment by cesar-galvao** [comment]
@beatrizmilz estou disponível para pegar esse!

**Comment by beatrizmilz** [comment]
> @beatrizmilz estou disponível para pegar esse!


Atualizei com o seu nome! Eu conversei com a Lu e nesse mês ela está mudando de país, então vai ficar bem difícil para ela fazer a revisão. Obrigada!

**Comment by beatrizmilz** [comment]
https://github.com/cienciadedatos/pt-r4ds/pull/80#issuecomment-2350926853
