### ISSUE TITLE
17 - transform.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#17]
Tradução: @arianacabral
Revisão 1: @beatrizmilz 
Revisão 2: @scopinho

**Comment by beatrizmilz** [comment]
Oieee! Anotei seu nome aqui :)

**Comment by beatrizmilz** [comment]
@arianacabral, quando puder, deixa algum comentário nessa issue?

**Comment by arianacabral** [comment]
Tudo certo! 😊

Qualquer coisa, é só falar 😉

Por esses dias, faço o PR do outro capítulo também, estou quase terminando a tradução.
