### ISSUE TITLE
19 - numbers.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#19]
Tradução: @scopinho 
Revisão 1: @carlossb1
Revisão 2: @beatrizmilz

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar para traduzir este também. thx

**Comment by scopinho** [comment]
Versão inicial no [PR 65](https://github.com/cienciadedatos/pt-r4ds/pull/65). 
Liberado para revisão.

**Comment by albersonmiranda** [comment]
Pessoas, saudações!

Apesar de já revisado, para a tradução de _double_, posso sugerir o uso de "real" ao invés de "ponto-flutuante"?

"Duplo" vem da precisão do flutuante (32-bits para precisão única e 64-bits para duplo). Ambos são aproximações de números reais, divergindo apenas na precisão.

Portanto, como _float_ representa tanto a aproximação 32-bits quanto a dupla (aliás, qualquer aproximação de parte fracionária  será _float_), ponto-flutuante, além de ser impreciso, é menos descritivo ao leitor do que apenas "real".

Aqui um exemplo do Hadley usando "real" para _double_:
![image](https://github.com/cienciadedatos/pt-r4ds/assets/45690517/727f08b3-e896-4d14-8d8d-8af30d40023d)
