### ISSUE TITLE
02 - preface-2e.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#2]
Tradução: @beatrizmilz 
Revisão 1: @nextmarte 
Revisão 2: @brunomioto

**Comment by nextmarte** [comment]
Posso pegar essa revisão

**Comment by beatrizmilz** [comment]
> Posso pegar essa revisão

Legal! Eu deixei vários prints no guia/wiki sobre como funciona a revisão. Se tiver alguma dúvida, me avisa!
Obrigada

**Comment by beatrizmilz** [comment]
obrigada @nextmarte e @brunomioto pela revisão!
