### ISSUE TITLE
20 - strings.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#20]
Tradução: @arianacabral 
Revisão 1: @magnotairone 
Revisão 2: @cesar-galvao 

Importante: Esse capítulo utiliza novos dados que precisamos traduzir no pacote [dados](https://github.com/cienciadedatos/dados). 
Essa tradução precisa ser feita em parceria com a tradução do capítulo, pois esses dados foram preparados para o capítulo, e precisa fazer sentido com os exemplos!

- https://github.com/cienciadedatos/dados/issues/89
- https://github.com/cienciadedatos/dados/issues/90
- https://github.com/cienciadedatos/dados/issues/91

**Comment by arianacabral** [comment]
Eu gostaria de contribuir com a tradução desse capítulo 😊

**Comment by beatrizmilz** [comment]
> Eu gostaria de contribuir com a tradução desse capítulo 😊

Oieee Ariana, tudo bem?
Seja bem vinda!

Essa é a primeira contribuição sua no projeto, certo?

Eu recomendaria você iniciar por um capítulo mais curto! Ex: https://github.com/cienciadedatos/pt-r4ds/issues/17
Pois  esse capítulo sobre strings é longo. 
Caso você queira mesmo começar pelo capítulo strings.qmd, eu posso te adicionar, mas me avise!


Você poderia entrar no canal do Slack? Lá é o lugar que estamos usando para conversar entre o time de tradução.
 [Slack da Latin-R](https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc), em um canal chamado #traducao-r4ds.

Materiais que são úteis:
https://github.com/cienciadedatos/pt-r4ds/wiki

https://cienciadedatos.github.io/guia-traducao-ptbr/ (estamos desenvolvendo ao longo desse projeto, então se algo não estiver claro, por favor me avise!)



Qualquer dúvida, me avise!

**Comment by arianacabral** [comment]
Oie, Bea! 

Tudo bem e vc? 

Essa será a minha primeira contribuição no projeto.  Então, por mim, sem problemas começar pelo [#17](https://github.com/cienciadedatos/pt-r4ds/issues/17). 

Eu já entrei no canal do Slack e olharei as discussões de vocês por lá. 

Obrigada pelas orientações e sugestões! Espero muito poder contribuir com o projeto.

**Comment by beatrizmilz** [comment]
> Oie, Bea!
> 
> Tudo bem e vc?
> 
> Essa será a minha primeira contribuição no projeto. Então, por mim, sem problemas começar pelo [#17](https://github.com/cienciadedatos/pt-r4ds/issues/17).
> 
> Eu já entrei no canal do Slack e olharei as discussões de vocês por lá.
> 
> Obrigada pelas orientações e sugestões! Espero muito poder contribuir com o projeto.

Tá bom! Coloquei seu nome por la :D

**Comment by arianacabral** [comment]
Obrigada! 😊

**Comment by beatrizmilz** [comment]
@arianacabral Deu certo a tradução daquele capítulo, uhuuuuul!
Você já tinha experiência usando o GitHub, certo?
Se quiser traduzir esse capítulo aqui, me avise.

**Comment by arianacabral** [comment]
Fico muito contente por ter contribuído com a tradução do capítulo 17.

Sim, eu tenho um pouco de experiência com o GitHub.  

Pode me incluir para traduzir esse capítulo também 😁

**Comment by beatrizmilz** [comment]
Uhul!

@arianacabral Coloquei seu nome!
Importante lembrar de criar uma nova branch pra fazer as modificações desse capítulo, se não elas são enviadas para o PR que já está aberto

**Comment by beatrizmilz** [comment]
Atualização: A @arianacabral disse que está quase terminando a tradução!

https://github.com/cienciadedatos/pt-r4ds/issues/17#issuecomment-1869770221

**Comment by beatrizmilz** [comment]
A @anacarolinamoreno  topou revisar esse capítulo!

**Comment by beatrizmilz** [comment]
Oi @anacarolinamoreno!
Se você precisar de alguma ajuda, me avisa.
Esse link pode ser útil: https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html
Atenção para a parte que comenta sobre esse botão: 
![imagem](https://github.com/user-attachments/assets/351db961-9309-4e22-a29b-e63a044e5ace)
Ele ajuda muito a deixar mais fácil para aceitar as sugestões depois!
<3

**Comment by beatrizmilz** [comment]
https://cienciadedatos.github.io/pt-r4ds/strings.html está no ar!! obrigada pessoal!
