### ISSUE TITLE
21 - regexps.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#21]
Tradução: @scopinho 
Revisão 1: @magnotairone
Revisão 2: @cesar-galvao

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me incluir na tradução deste também. Thx

OBS: Este cap. usa o babynames (dados:bebes). Observei que a variável sexo (F/M Female/Male) está ainda em inglês. Não sei se foi de propósito, mas se não me engano, outro dataset a variável foi trocada para M/F Masculino/Feminino.

**Comment by scopinho** [comment]
Versão inicial traduzida submetida no[ PR #66 ](https://github.com/cienciadedatos/pt-r4ds/pull/66).
@beatrizmilz ..liberado para iniciar revisões.

**Comment by scopinho** [comment]
@beatrizmilz ...Apenas pra constar aqui no issue tb, o @magnotairone fez a 1a revisão no PR66. Aguardando o segundo revisor. Thx

**Comment by cesar-galvao** [comment]
@beatrizmilz pode me botar de segundo revisor?

**Comment by beatrizmilz** [comment]
> @beatrizmilz pode me botar de segundo revisor?

Claro!!

**Comment by beatrizmilz** [comment]
Valeu pessoal! Agora só falta aceitar as sugestões. Logo logo faço isso!

**Comment by beatrizmilz** [comment]
https://cienciadedatos.github.io/pt-r4ds/regexps.html está ao vivo!
