### ISSUE TITLE
22 - factors.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#22]
Tradução: @scopinho 
Revisão 1: @cesar-galvao 
Revisão 2: @arianacabral

**Comment by scopinho** [comment]
Ola @beatrizmilz , pode me colocar como tradutor desse também. Thx

**Comment by scopinho** [comment]
Versão inicial da traudção feita no[ PR #67 ](https://github.com/cienciadedatos/pt-r4ds/pull/67).
Liberado para iniciar as revisões.

**Comment by cesar-galvao** [comment]
@beatrizmilz pode me botar de revisor 1 desse!

**Comment by beatrizmilz** [comment]
> [@beatrizmilz](https://github.com/beatrizmilz) pode me botar de revisor 1 desse!

Só vi agora, desculpa! anotando aqui!

**Comment by scopinho** [comment]
@beatrizmilz @cesar-galvao , a @arianacabral já fez a 1a revisão. Os comentários acabaram ficando no PR e nao aqui no issue.

**Comment by cesar-galvao** [comment]
@scopinho Como faz pra revisar entao?

**Comment by scopinho** [comment]
> @scopinho Como faz pra revisar entao?

Oi @cesar-galvao , basta entrar no Pull Request [67](
https://github.com/cienciadedatos/pt-r4ds/pull/67)
E fazer a revisão normalmente como se fosse uma 1a revisão. Eu irei receber as mudanças que vc sugerir e fazer os commits no PR. Qq dúvida me avise. Muito obrigado!

**Comment by cesar-galvao** [comment]
@beatrizmilz acho que tivemos um probleminha de fluxo nessa issue, mas o elenco correto é o abaixo. Já está na etapa de 2a revisão!

Tradução: @scopinho
Revisão 1: @arianacabral
Revisão 2: @cesar-galvao

**Comment by beatrizmilz** [comment]
Uhul! esta no ar!!!
