### ISSUE TITLE
23 - datetimes.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#23]
Tradução: @scopinho 
Revisão 1: @magnotairone 
Revisão 2: @cesar-galvao
Revisão 3: @beatrizmilz

**Comment by scopinho** [comment]
oi @beatrizmilz , pode me colocar como tradutor para este também. thx

**Comment by scopinho** [comment]
Tradução inicial submetida pelo [PR 68 ](https://github.com/cienciadedatos/pt-r4ds/pull/68).
Liberado para iniciar revisões.

**Comment by beatrizmilz** [comment]
A @anacarolinamoreno  topou revisar esse capítulo!

**Comment by beatrizmilz** [comment]
Oi @anacarolinamoreno!
Se você precisar de alguma ajuda, me avisa.
Esse link pode ser útil: https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html
Atenção para a parte que comenta sobre esse botão: 
![imagem](https://github.com/user-attachments/assets/351db961-9309-4e22-a29b-e63a044e5ace)
Ele ajuda muito a deixar mais fácil para aceitar as sugestões depois!
<3

**Comment by cmusso86** [comment]
Se ainda precisar de um segundo revisor, posso contribuir.

**Comment by beatrizmilz** [comment]
Prontoooo está no ar!! Obrigada pessoal!

https://cienciadedatos.github.io/pt-r4ds/datetimes.html

@scopinho @cesar-galvao
@magnotairone
