### ISSUE TITLE
24 - missing-values.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#24]
Tradução: @scopinho 
Revisão 1: @magnotairone
Revisão 2: @brunomioto

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor desse tb. Thx!

**Comment by scopinho** [comment]
Versão inicial da tradução no [PR 69 ](https://github.com/cienciadedatos/pt-r4ds/pull/69).
Liberado para iniciar revisões.

**Comment by brunomioto** [comment]
Oi @beatrizmilz , vou revisar!

**Comment by beatrizmilz** [comment]
Obrigada Bruno!!

**Comment by beatrizmilz** [comment]
Está no ar!! Muito obrigada @scopinho @magnotairone @brunomioto !!

https://cienciadedatos.github.io/pt-r4ds/missing-values.html

**Comment by scopinho** [comment]
> Está no ar!! Muito obrigada @scopinho @magnotairone @brunomioto !!
> 
> https://cienciadedatos.github.io/pt-r4ds/missing-values.html

Show de bola pessoal!!! Mais um pra conta!! Muito obrigado @beatrizmilz !!!
