### ISSUE TITLE
25 - joins.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#25]
Tradução: @scopinho 
Revisão 1: @MaximilianCF 
Revisão 2: @debora-s

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor deste tb. thx!

**Comment by scopinho** [comment]
oi @beatrizmilz ...Tradução inicial do joins.qmd submetida pelo [PR](https://github.com/cienciadedatos/pt-r4ds/pull/70) .
Liberado para iniciar revisões.

**Comment by MaximilianCF** [comment]
Oi @beatrizmilz Posso fazer a revisão deste capítulo.

**Comment by beatrizmilz** [comment]
> Oi @beatrizmilz Posso fazer a revisão deste capítulo.

Eba! Adicionado!

O fluxo de revisão é diferente da tradução. 
Esse texto pode ser útil:
https://cienciadedatos.github.io/guia-traducao-ptbr/revisando-github.html

**Comment by MaximilianCF** [comment]
Blz...show de bola.

Estou lendo o texto sugerido.
Tks

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPT0lYMktPNlJQNjVKTUpRSzZFREhNUlhFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho

**Comment by beatrizmilz** [comment]
Para registro: a @debora-s entrou em contato comigo via email e vai contribuir revisando esse capítulo!

**Comment by MaximilianCF** [comment]
Bom Dia Bia,

Ok vou aguardar contato. Estive envolvido desde março com um trabalho grande e não pude dar atenção à tradução e o mês de maio aqui para o RS foi literalmente vaporizado do calendário. Retomando a tradução.
Obrigado.
Att.,

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTEFKWFRMNEdORTdNVTRCNldFUVc2N1BFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho

**Comment by debora-s** [comment]
Olá @MaximilianCF  Vou inicar a revisão deste capítulo, ok?

**Comment by beatrizmilz** [comment]
> Bom Dia Bia, Ok vou aguardar contato. Estive envolvido desde março com um trabalho grande e não pude dar atenção à tradução e o mês de maio aqui para o RS foi literalmente vaporizado do calendário. Retomando a tradução. Obrigado. Att., Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTEFKWFRMNEdORTdNVTRCNldFUVc2N1BFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho
> […](#)
> On jun 24 2024, at 5:54 pm, Beatriz Milz ***@***.***> wrote: Para registro: a @debora-s ***@***.***/1?redirect=https%3A%2F%2Fgithub.com%2Fdebora-s&recipient=cmVwbHkrQVdBUUhPTEFKWFRMNEdORTdNVTRCNldFUVc2N1BFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D) entrou em contato comigo via email e vai contribuir revisando esse capítulo! — Reply to this email directly, view it on GitHub ***@***.***/2?redirect=https%3A%2F%2Fgithub.com%2Fcienciadedatos%2Fpt-r4ds%2Fissues%2F25%23issuecomment-2187384729&recipient=cmVwbHkrQVdBUUhPTEFKWFRMNEdORTdNVTRCNldFUVc2N1BFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D), or unsubscribe ***@***.***/3?redirect=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWAQHONX4ESJWBLPKM5RJ73ZJCBPPAVCNFSM6AAAAABJ2RE7NGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOBXGM4DINZSHE&recipient=cmVwbHkrQVdBUUhPTEFKWFRMNEdORTdNVTRCNldFUVc2N1BFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D). You are receiving this because you were mentioned.

Oi @MaximilianCF ! Fica tranquilo.

Nossa, não sabia que você era do RS! Espero que esteja tudo bem com você e sua família (na medida do possível) :(

**Comment by MaximilianCF** [comment]
Bom Dia Beatriz,

Moro no extremo sul do RS em Pelotas. Aqui tivemos bairros alagados mas nem se compara com as outras cidades.
Vou combinar com a Debora para dividir a revisão.

Novamente, desculpe pelo atraso e por eventuais atrasos na tradução.
Abraços,

Enviado do Mailspring ***@***.***/0?redirect=https%3A%2F%2Fgetmailspring.com%2F&recipient=cmVwbHkrQVdBUUhPTUhRNlczVzU1VzVMQko0RU9FUkJUTVhFVkJOSEhIQTRNVFE0QHJlcGx5LmdpdGh1Yi5jb20%3D), o melhor aplicativo de email gratuito para o trabalho

**Comment by beatrizmilz** [comment]
Obrigada pessoal!  O capítulo traduzido está online! https://cienciadedatos.github.io/pt-r4ds/joins.html

**Comment by scopinho** [comment]
> Obrigada pessoal! O capítulo traduzido está online! https://cienciadedatos.github.io/pt-r4ds/joins.html

Muito obrigado pela ajuda pessoal!
