### ISSUE TITLE
27 - spreadsheets.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#27]
Tradução: @scopinho 
Revisão 1: @carlossb1 
Revisão 2: @decarvaa

**Comment by beatrizmilz** [comment]
Adicionado, @scopinho ! Obrigada!

**Comment by decarvaa** [comment]
@beatrizmilz, pode me colocar como segundo revisor desse? 
Valeu valeu!

**Comment by beatrizmilz** [comment]
> @beatrizmilz, pode me colocar como segundo revisor desse? Valeu valeu!

Adicionado!

**Comment by beatrizmilz** [comment]
Pessoal, muito obrigada! Aceitei o PR :)

**Comment by scopinho** [comment]
> Pessoal, muito obrigada! Aceitei o PR :)

Aeeee..mais um pra conta!!! ;-) Muito obrigado pessoal!
