### ISSUE TITLE
28 - databases.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#28]
Tradução: @scopinho
Revisão 1: @Luaaalex 
Revisão 2: @beatrizmilz

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor deste também.

**Comment by scopinho** [comment]
Tradução inicial feita no [PR #59](https://github.com/cienciadedatos/pt-r4ds/pull/59). Pronto para iniciar a revisão.

**Comment by beatrizmilz** [comment]
Tradução completa :)
