### ISSUE TITLE
29 - arrow.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#29]
Tradução: @scopinho 
Revisão 1: @decarvaa 
Revisão 2: @beatrizmilz

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor deste do arrow também.

**Comment by decarvaa** [comment]
Oi @beatrizmilz e @scopinho! Posso revisar esse aqui tb!

**Comment by scopinho** [comment]
Tradução inicial feita no [PR 60](https://github.com/cienciadedatos/pt-r4ds/pull/60). Revisão pode ser iniciada.
