### ISSUE TITLE
05 - data-visualize.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#3]
Tradução: Bruno Mioto @brunomioto

Revisão 1:  @nextmarte 

Revisão 2: @beatrizmilz

**Comment by brunomioto** [comment]
Algumas traduções que estou seguindo, e seria importante mantermos um padrão (e fico aberto à sugestões)

- mapping: mapeamento
- aesthetics: atributos estéticos
- scaling: dimensionamento
- geometrical object: geometria
- the geom: a geometria
- labels: rótulos (eu até pensei em títulos mas pode ficar confuso)

**Comment by nextmarte** [comment]
@beatrizmilz @brunomioto posso fazer a primeira revisão

**Comment by beatrizmilz** [comment]
> Algumas traduções que estou seguindo, e seria importante mantermos um padrão (e fico aberto à sugestões)
> 
>     * mapping: mapeamento
> 
>     * aesthetics: atributos estéticos
> 
>     * scaling: dimensionamento
> 
>     * geometrical object: geometria
> 
>     * the geom: a geometria
> 
>     * labels: rótulos (eu até pensei em títulos mas pode ficar confuso)
> 
>     * binwidth: largura de intervalo
> 
>     * data frame: data frame

adicionei na wiki! https://github.com/cienciadedatos/pt-r4ds/wiki/3-%E2%80%90-Guia-de-contribui%C3%A7%C3%A3o-com-a-tradu%C3%A7%C3%A3o-do-livro-%22R-for-Data-Science-(2e)%22 se mudar, podemos mudar na wiki também

**Comment by beatrizmilz** [comment]
Eu começei dando joinha nas contribuições do @nextmarte que eu concordava mas acabei desistindo, são muitas hahaha então se tiver algo que eu penso diferente, eu comento na thread específica, ok?

**Comment by beatrizmilz** [comment]
Uma coisa que pode ser confusa é que ggplot é usado para mais de uma forma em inglês.

Pensei em anotar assim na wiki, baseado no que vi que vocês traduziram:
 

- ggplot() - quando se trata da função -> a função ggplot()
- ggplot - quando se trata do pacote -> o ggplot
- ggplot - quando se trata de um gráfico -> um gráfico ggplot

**Comment by nextmarte** [comment]
Tbm acho legal específicar gráfico ggplot, pq em inglês tem o jogo de palavras em que o ggplot quer dizer justamente um gráfico ggplot

**Comment by beatrizmilz** [comment]
🎉 tradução concluida! parabens e obrigada @brunomioto @nextmarte
