### ISSUE TITLE
30 - rectangling.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#30]
Tradução: @scopinho 
Revisão 1: @cmusso86
Revisão 2: @debora-s

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor deste também... mas já tenho algumas dúvidas/observações ;-)

Para o "rectangling.qmd": 

1-) rectangling = representação retangular ?
2-) o capítulo usa do pacote 'repurrrsive':
 
got_chars - lista não-nomeada (unnamed list)
gmaps_cities - tibble 2 colunas e 5 linhas
gh_users - lista não-nomeada

Acredito que precisaremos adicionar ao "dados", mas não sei se o esquema de tradução com os yamls funcionaria para listas tb.

3-) O pacote gh_users_json() que pega o json de dentro do pacote repurrrsive.
Isto ocorre em outras situações tb e ainda não sei se já foi discutido como lidaremos com estes cenários de funções dentro dos pacotes que pegam o dataset automaticamente. Alguma ideia?

**Comment by beatrizmilz** [comment]
Oiee!
Sobre o 2:
Podemos adicionar no dados criando uma pasta no data-raw e criando uma lista por lá, e disponibilizando no pacote. Vou iniciar a estrutura.

Sobre o 3: Não tenho certeza! precisamos pensar.

**Comment by beatrizmilz** [comment]
Está online! https://cienciadedatos.github.io/pt-r4ds/rectangling.html obrigada pessoal!
