### ISSUE TITLE
31 - webscraping.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#31]
Tradução: @scopinho 
Revisão 1: @carlosssb1
Revisão 2: @cesar-galvao

**Comment by scopinho** [comment]
Olá @beatrizmilz , pode me colocar como tradutor deste também.

**Comment by scopinho** [comment]
Tradução inicial feita e submetida no [PR #62](https://github.com/cienciadedatos/pt-r4ds/pull/62). Liberada para revisões.

**Comment by cesar-galvao** [comment]
@beatrizmilz posso ser o segundo revisor

**Comment by cesar-galvao** [comment]
@scopinho eu vou fazer a revisao desse tb!

@beatrizmilz acho que a minha mensagem passou batida kkkk mas vou fazer esse amanhã.

**Comment by beatrizmilz** [comment]
> @scopinho eu vou fazer a revisao desse tb!
> 
> @beatrizmilz acho que a minha mensagem passou batida kkkk mas vou fazer esse amanhã.

Oi @cesar-galvao ! Desculpa! Tinha passado batido mesmo... te adicionei como segundo revisor!
