### ISSUE TITLE
32 - program.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#32]
Tradução: @ligialouzada 
Revisão 1: @beatrizmilz 
Revisão 2: @scopinho

**Comment by ligialouzada** [comment]
Beatriz, posso traduzir esse capítulo.

**Comment by beatrizmilz** [comment]
ótimo! se precisar de ajuda me avisa!

**Comment by scopinho** [comment]
Olá pessoal, posso fazer a 2a revisão deste também.

**Comment by beatrizmilz** [comment]
Aceitei o PR! 🚀
