### ISSUE TITLE
33 - functions.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#33]
Tradução: @scopinho 
Revisão 1: @carlossb1
Revisão 2: @cesar-galvao

**Comment by scopinho** [comment]
ola @beatrizmilz , pode me colocar como tradutor deste tb? thx

**Comment by scopinho** [comment]
Tradução inicial submetida no [PR 74. ](https://github.com/cienciadedatos/pt-r4ds/pull/72).
Liberado para iniciar revisões.

**Comment by cesar-galvao** [comment]
@beatrizmilz pode me botar de segundo revisor?

**Comment by beatrizmilz** [comment]
Claro! Pode começar se quiser, eu atualizo logo logo na issue!

Em qua., 3 de abr. de 2024 às 10:52, Cesar A. Galvao <
***@***.***> escreveu:
