### ISSUE TITLE
34 - iteration.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#34]
Tradução: @scopinho 
Revisão 1: @cmusso86
Revisão 2: @debora-s

**Comment by scopinho** [comment]
ola @beatrizmilz , pode me colocar como tradutor desse tb? Pergunta, por acaso já foi discutido antes a questão do gapminder que fica dentro do livro por acaso? Thx

**Comment by beatrizmilz** [comment]
Oieee!

O gapminder está traduzido no pacote dados, como dados_gapminder:  

https://cienciadedatos.github.io/dados/reference/dados_gapminder.html

**Comment by scopinho** [comment]
ok, mas neste cap. ele bao usa o dataframe, mas sim varios arquivos Excel que estao.em data/gapminder/*.xlsx.
Como acha que podíamos ter este diretorio des .xlsx em pt-br? Talvez precisemos criar um outro folder em.algum lugar nao?

**Comment by beatrizmilz** [comment]
> ok, mas neste cap. ele bao usa o dataframe, mas sim varios arquivos Excel que estao.em data/gapminder/*.xlsx. Como acha que podíamos ter este diretorio des .xlsx em pt-br? Talvez precisemos criar um outro folder em.algum lugar nao?

Ahhhhh, entendi!
E esse data/gapminder/... como é obtido? Baixando um zip no capítulo? (perguntando pra me situar)

**Comment by scopinho** [comment]
> > ok, mas neste cap. ele bao usa o dataframe, mas sim varios arquivos Excel que estao.em data/gapminder/*.xlsx. Como acha que podíamos ter este diretorio des .xlsx em pt-br? Talvez precisemos criar um outro folder em.algum lugar nao?
> 
> Ahhhhh, entendi! E esse data/gapminder/... como é obtido? Baixando um zip no capítulo? (perguntando pra me situar)

Parece que ele fez algo offline, pegando 12 anos do gapminder e criando um .xlxs por ano e jogando no data/gapminder. Mas não achei no livro um codigo que fizesse isso. Ele só chega menta que tem 12 arquivos .xlsx vindos do gapminder. :-/

**Comment by scopinho** [comment]
oi @beatrizmilz ...Versão inicial da tradução no [PR 75 ](https://github.com/cienciadedatos/pt-r4ds/pull/75). Podem iniciar as reviões. Fiz um comentário lá sobre o gapminder...talvez a gente não precise traduzir.

**Comment by cesar-galvao** [comment]
@beatrizmilz posso entrar nesse também se quiser adiantar!

**Comment by beatrizmilz** [comment]
> @beatrizmilz posso entrar nesse também se quiser adiantar!

César, a Debora disse que está fazendo! 
Os  PRs #79  e #68 estão com a Carol Moreno, mas ela não comentou nada, então não sei se ainda vai fazer. Se quiser colaborar com a revisão de algum deles (ou deles) é bem vindo!!

**Comment by beatrizmilz** [comment]
https://github.com/cienciadedatos/pt-r4ds/pull/75#issuecomment-2455421612
