### ISSUE TITLE
35 - base-R.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#35]
Tradução: @scopinho 
Revisão 1: @magnotairone 
Revisão 2: @cesar-galvao

**Comment by scopinho** [comment]
oi @beatrizmilz , pode me colocar como tradutor desse tb. thx

**Comment by scopinho** [comment]
oi @beatrizmilz . Tradução inicial do base-R.qmd feita no [PR 71](https://github.com/cienciadedatos/pt-r4ds/pull/71).
Liberado para revisões.
Thx

**Comment by cesar-galvao** [comment]
@beatrizmilz revisão feita.

**Comment by scopinho** [comment]
oi @beatrizmilz , as duas revisões feitas. Acredito que podemos concluir mais este. Thx
