### ISSUE TITLE
37 - quarto.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#37]
Tradução: @cesar-galvao 
Revisão 1: @beatrizmilz 
Revisão 2: @cmusso86

**Comment by beatrizmilz** [comment]
O @cesar-galvao disse que quer traduzir esse capítulo!

**Comment by cesar-galvao** [comment]
@beatrizmilz Essa eu pego

**Comment by cesar-galvao** [comment]
@beatrizmilz concluído e fiz o pull request.

**Comment by beatrizmilz** [comment]
Obrigada Cesar! Vou fazer a primeira revisão!
