### ISSUE TITLE
38 - quarto-formats.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#38]
Tradução: @cesar-galvao 
Revisão 1: @beatrizmilz 
Revisão 2: @brunomioto

**Comment by beatrizmilz** [comment]
O @cesar-galvao disse que quer traduzir esse capítulo!

**Comment by cesar-galvao** [comment]
@beatrizmilz eu pego esse também

**Comment by beatrizmilz** [comment]
Está no ar! https://cienciadedatos.github.io/pt-r4ds/quarto-formats.html
Obrigada @cesar-galvao @brunomioto!
