### ISSUE TITLE
03 - intro.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#4]
Tradução: Beatriz @beatrizmilz 
Revisão 1: Halian @halian-vilela 
Revisão 2: @albersonmiranda

**Comment by beatrizmilz** [comment]
Nesse capítulo, creio que é interessante adicionar um parágrafo sobre a instalação do pacote dados

**Comment by halian-vilela** [comment]
@beatrizmilz Oi Bea! Pode me colocar como o primeiro revisor? Já iniciei (só lendo) no início da semana, mas ainda não coloquei nenhum comentário.

Valeu!

**Comment by beatrizmilz** [comment]
Sim!

Em dom., 8 de out. de 2023 às 15:13, Halian Vilela ***@***.***>
escreveu:

**Comment by beatrizmilz** [comment]
Halian, a revisão é nesse arquivo aqui: https://github.com/cienciadedatos/pt-r4ds/pull/44/files

(se já estava claro, desculpe a repetição haha)
