### ISSUE TITLE
06 - workflow-basics.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#6]
Tradutor: @nextmarte 
Revisão 1: @beatrizmilz 
Revisão 2: @SCOPINHO

**Comment by nextmarte** [comment]
@beatrizmilz posso começar por esse

**Comment by beatrizmilz** [comment]
Legal @nextmarte ! 

Eu comecei a escrever um guia aqui: https://github.com/cienciadedatos/pt-r4ds/wiki/Guia-de-contribui%C3%A7%C3%A3o-com-a-tradu%C3%A7%C3%A3o-do-livro-%22R-for-Data-Science-(2e)%22

Se tiver dúvidas, pode me chamar no Slack e podemos fazer uma chamada rápida se quiser.
