### ISSUE TITLE
07 - data-transform.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#7]
Tradução: @halian-vilela 
Revisão 1: @Luaaalex 
Revisão 2: @cesar-galvao

**Comment by halian-vilela** [comment]
Oi @beatrizmilz 

Pode botar mais esse para eu traduzir? Terminei o outro, hoje de tarde eu subo pra revisão, estou offline agora, mas já consigo iniciar esse. 

Valeu!

**Comment by beatrizmilz** [comment]
Vou colocar! Obrigada !

**Comment by Luaaalex** [comment]
Eu posso seguir com essa revisão.

**Comment by beatrizmilz** [comment]
> Eu posso seguir com essa revisão.

Ok Lu! O @halian-vilela ainda está traduzindo o capítulo. Quando ele enviar, aviso por aqui!

**Comment by beatrizmilz** [comment]
Oi @halian-vilela ! Tudo bem? Como anda a tradução desse capítulo? Precisa de algo? Obrigada!

**Comment by halian-vilela** [comment]
@beatrizmilz 

Oi Bea! Mals pela ausência, esse início de ano foi meio corridão, eu fiquei sem tempo de continuar! Mas eu já to continuando, fecho ele até o final do Carvanaval, blz?

**Comment by beatrizmilz** [comment]
> @beatrizmilz
> 
> Oi Bea! Mals pela ausência, esse início de ano foi meio corridão, eu fiquei sem tempo de continuar! Mas eu já to continuando, fecho ele até o final do Carvanaval, blz?

Sem pressão!!! Curte o carnaval, não precisa se preocupar hahaa. Eu escrevi perguntando em todas as traduções que estão em andamento para checar mesmo se as pessoas precisam de algo (ou se desistiram, etc 👀 ).
Bom carnaval!!

**Comment by beatrizmilz** [comment]
Oi Halian!
@halian-vilela Tudo bem? Tem alguma novidade?
Se você estiver sem disponibilidade, você pode enviar o que já foi feito, e a gente continua com outra pessoa, sem problemas!

**Comment by halian-vilela** [comment]
Tá na mão, @beatrizmilz 

https://github.com/cienciadedatos/pt-r4ds/pull/97

Foi mal pela demora absurda! O capítulo nem era difícil o lance foi q ele foi sumindo algumas vezes da minha vista de coisas "a fazer" e eu acabava esquecendo que tava pendente!

Mas é isso aí, vou tentar ser mais pontual nos próximos, talvez pegar alguns para revisar para a gente desovar a leva de PRs abertas e aí eu me reorganizo para traduzir mais alguns.

**Comment by Luaaalex** [comment]
Obrigada @halian-vilela .
@beatrizmilz vou finalizar a revisão até domingo 05/5 ;)

**Comment by beatrizmilz** [comment]
> Tá na mão, @beatrizmilz
> 
> #97
> 
> Foi mal pela demora absurda! O capítulo nem era difícil, o lance foi q ele foi sumindo algumas vezes da minha vista de coisas "a fazer" e eu acabava esquecendo que tava pendente!
> 
> Mas é isso aí, vou tentar ser mais pontual nos próximos, talvez pegar alguns para revisar para a gente desovar a leva de PRs abertas e aí eu me reorganizo para traduzir mais alguns.

Tudo bem!! Uhull! Vamos para revisão...

**Comment by Luaaalex** [comment]
@halian-vilela obrigada pela tradução. 
@beatrizmilz  revisão pronta :)
O ponto que gerou dúvida na tradução foi o ` summary` e `summary statistics`, como pontuado por Halian. 
Abs,

**Comment by beatrizmilz** [comment]
Obrigadaaaa Lu!!

**Comment by beatrizmilz** [comment]
Pode fazer!!! Uhul obrigada

**Comment by beatrizmilz** [comment]
Pessoal, está online!!

https://cienciadedatos.github.io/pt-r4ds/data-transform.html

Muito obrigada!
