### ISSUE TITLE
08 - workflow-style.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#8]
Tradução: @nextmarte 
Revisão 1: @beatrizmilz
Revisão 2: @decarvaa

**Comment by nextmarte** [comment]
Posso pegar esse também, continuando com os capítulos de workflow.

**Comment by beatrizmilz** [comment]
> Posso pegar esse também, continuando com os capítulos de workflow.

Ótimo! Obrigada! Marquei você na issue :)
