### ISSUE TITLE
Erro 1.7 - Problemas comuns

### ISSUE THREAD

**Issue by Ludimilajuliele** [cienciadedatos/pt-r4ds#87]
"Todos nós estamos escrevendo código em R há anos, mas todos os dias ainda escrevemos códigos que não **funciona** na primeira tentativa!"
Correto = **Funcionam**

**Comment by beatrizmilz** [comment]
Oi @Ludimilajuliele !! Muito obrigada!
Só vi hoje, mas adicionei aqui!

**Comment by beatrizmilz** [comment]
Arrumado! Obrigada! 
https://cienciadedatos.github.io/pt-r4ds/data-visualize.html#problemas-comuns
