### ISSUE TITLE
Código do exercicio 6 no topico 1.5.5

### ISSUE THREAD

**Issue by KarinaFerraraBarros** [cienciadedatos/pt-r4ds#88]
problema na tradução da linha final: labs(color = Species). No portugues está como especie, idêntico ao nome da variável, o que faz com que não sejam criadas duas legendas (o exercício pede para resolver esse problema no código). 
```
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(color = "Species")



ggplot(
  data = pinguins,
  mapping = aes(
    x = comprimento_bico, y = profundidade_bico, 
    color = especie, shape = especie
  )
) +
  geom_point() +
  labs(color = "especie")
```

**Comment by beatrizmilz** [comment]
Olá!
Arrumei, obrigada por observar!!
![imagem](https://github.com/cienciadedatos/pt-r4ds/assets/42153618/f7abd985-237a-44c7-9ec7-5f1fe4a98d2b)
https://cienciadedatos.github.io/pt-r4ds/data-visualize.html
