### ISSUE TITLE
09 - data-tidy.qmd

### ISSUE THREAD

**Issue by beatrizmilz** [cienciadedatos/pt-r4ds#9]
Tradução: @halian-vilela 
Revisão 1: @scopinho 
Revisão 2: @beatrizmilz

**Comment by halian-vilela** [comment]
Oi! @beatrizmilz Pode fazer o assign desse capítulo para mim? Obrigado!

**Comment by beatrizmilz** [comment]
Feito! O fluxo para traduzir tá claro? Precisa de ajuda para iniciar?

**Comment by halian-vilela** [comment]
Tá sim! Só fork e PR pra esse repo, né? Amanhã inicio, dia hoje foi caótico... Valeu!

**Comment by beatrizmilz** [comment]
> Tá sim! Só fork e PR pra esse repo, né? Amanhã inicio, dia hoje foi caótico... Valeu!

Isso!
https://github.com/cienciadedatos/pt-r4ds/wiki/4-%E2%80%90-Como-enviar-uma-tradu%C3%A7%C3%A3o

Só cuidado para não enviar o PR para o livro em inglês 😆

**Comment by scopinho** [comment]
@beatrizmilz / @halian-vilela ..pretendo ajudar na revisão de capítulo. Pode ser?

**Comment by beatrizmilz** [comment]
> @beatrizmilz / @halian-vilela ..pretendo ajudar na revisão de capítulo. Pode ser?

Olá!! Pode ser sim.
Essa é a sua primeira revisão no projeto, né? Recomendo dar uma checada nesses dois arquivos:
https://github.com/cienciadedatos/pt-r4ds/wiki/5-%E2%80%90-Como-fazer-uma-revis%C3%A3o
https://github.com/cienciadedatos/pt-r4ds/wiki/3-%E2%80%90-Guia-de-contribui%C3%A7%C3%A3o-com-a-tradu%C3%A7%C3%A3o-do-livro-%22R-for-Data-Science-(2e)%22

**Comment by scopinho** [comment]
Oi @beatrizmilz . Sim, já estou lendo o Guia e me inteirando dos processos para a tradução/revisão.
**Perguntinha**: Vi que o @halian-vilela colocou bons comentários com a questão da tradução de (_tidy_) e suas variações. Como este é um termo chave que aparece em diversos capítulos também, discutimos lá nos comentários mesmo, ou seria interessante ouvir os demais lá no Slack antes e fecharmos uma abordagem mais geral, o que acham??

**Comment by beatrizmilz** [comment]
acho legal discutir no slack!  você pode postar lá? (aliás, vc já está por lá? se não, posso te adicionar!)
tem um outro capítulo que falamos um pouco disso, o @albersonmiranda deu sugestões. posso resgatar as sugestões dele, e responder no slack.

**Comment by beatrizmilz** [comment]
@scopinho agora que eu vi que você já está lá, e o @halian-vilela já postou! Boa!

**Comment by beatrizmilz** [comment]
Oi pessoal! 
@halian-vilela , eu mesma aceitei as sugestões no capítulo, tudo bem?

Ele está disponível aqui:
https://cienciadedatos.github.io/pt-r4ds/data-tidy.html

Podemos fazer outro PR posteriormente se necessário (ex. percebermos que faltou alto!)

Muito obrigada @scopinho e @halian-vilela!

**Comment by halian-vilela** [comment]
@beatrizmilz 

Blz! Foi mal o sumiço! Esse último mês foi corrito, mas to voltando por agora, devo mandar o próximo capítulo no início da próxima semana!

Abraços e feliz ano novo!
