### ISSUE TITLE
Sugestão de alteração - Capítulo Visualização de Dados

### ISSUE THREAD

**Issue by MicheleCaramigo** [cienciadedatos/pt-r4ds#92]
Segue sugestão para ajudar na fluidez da leitura.
Analisando o texto em inglês cheguei a sugestão abaixo.

1. Visualização de Dados
1.1.1 Pre requisitos

Versão original:

> Além do tidyverse, nós também usaremos o pacote dados, que **inclui várias bases de dados**, incluindo um com medidas corporais de pinguins de três ilhas.....

Sugestão para reescrever esse trecho:

> Além do tidyverse, nós também usaremos o pacote dados, que **contém** várias bases de dados, incluindo **uma** com medidas corporais de pinguins de três ilhas....

**Comment by beatrizmilz** [comment]
Muito obrigada @MicheleCaramigo ! Feito!
